### ISSUE TITLE
Images when drawn are distorted or has a weird flashing feeling

### ISSUE THREAD

**Issue by hisRoyalty** [newtykins/canvas-gif#8]
For the branch `v2`

![Image](https://user-images.githubusercontent.com/88897968/163910703-3a742294-1bfd-42b8-905a-3c16f5874fff.png)
^ to reproduce, use the `drawImage()` method on a gif.

**Comment by hisRoyalty** [comment]
@newtykins _If not possible_, I'll continue to use [GraphicsMagick](http://graphicsmagick.org/) or [ImageMagick](https://imagemagick.org/). If possible, please let me know, as this is colliding with one of my [Project's Issue](https://github.com/Im-Ace-1234/Disvas/issues/2).

**Comment by isitreallyalive** [comment]
Working on letting GraphicsMagick binaries be packaged with canvas-gif to be used as a compiler and potentially as a future replacement for sharp as it's footprint is pretty negligible, and performance is still better than that of node-canvas.

You can keep a track on the binary package's development [here](https://github.com/newtykins/gm-binaries) (:

**Comment by isitreallyalive** [comment]
The latest commit has a gm encoder anyway if you already have it installed globally!

**Comment by hisRoyalty** [comment]
> Working on letting GraphicsMagick binaries be packaged with canvas-gif to be used as a compiler and potentially as a future replacement for sharp as it's footprint is pretty negligible, and performance is still better than that of node-canvas.
> 
> You can keep a track on the binary package's development [here](https://github.com/newtykins/gm-binaries) (:



Awesome!

**Comment by hisRoyalty** [comment]
> The latest commit has a gm encoder anyway if you already have it installed globally!



Yeah I've seen it.
